### ISSUE TITLE
Некоторые сообщения дублируются

### ISSUE THREAD

**Issue by Suzanskyi** [ivan909020/shop-telegram-bot#1]
В целом работа бота отличная, мне очень нравится ваша задумка и реализация. 
![image](https://user-images.githubusercontent.com/18307543/75235233-91d3ba00-57c4-11ea-9651-053230786675.png)

**Comment by ivan-zaitsev** [comment]
Спасибо, в свободное время постараюсь исправить.

**Comment by ivan-zaitsev** [comment]
Fixed with commit 83b141ea381d03efb31d604c5043d7d2d3c5ba63
