### ISSUE TITLE
Ошибка в админке 

### ISSUE THREAD

**Issue by Suzanskyi** [ivan909020/shop-telegram-bot#2]
![image](https://user-images.githubusercontent.com/18307543/75235333-b92a8700-57c4-11ea-9e26-b1e99c8aa233.png)

**Comment by ivan-zaitsev** [comment]
Спасибо, в свободное время постараюсь исправить.

**Comment by ivan-zaitsev** [comment]
Fixed with commit a6366787449b9fd6732c0022bebbf033e38f8355
